# =====================================================
#  Echo Plugin – Configuration (v0.1 BETA)
#  Customize all messages and menus here.
#  Color codes (&a, &6, &7) and HEX (<#RRGGBB>) are supported.
# =====================================================

# Controls which language is used for messages and GUIs.
# Supported: en, hu
lang: en

# Enables the %world% placeholder in messages.
# true = players can use %world%, false = placeholder is disabled
ph-world-enabled: true

# Permission used for administrative commands like token management, message wiping, etc.
admin-permission: echo.admin

# CURRENTLY NOT IMPLEMENTED FEATURE
# Sets the currency used for setting messages
# Possible currencies: money (vault), token (echo)
# currency: token
# amount: 1

# Menu configuration
glowing-items: true

# Title settings when players set a message.
title-enabled: true
title-main: "§aMessage Editing"
title-sub: "§7Type your desired §6join§7/§6leave §7message in the chat."

# Checks for plugin updates on startup.
# Recommended: true (keeps you up-to-date)
# Warning: disabling may cause you to miss important fixes.
check-updates: true